### OAuth2 Client Credentials flow (machine-to-machine, no end user login)
# Prerequisites:
# 1) Start authorization server: ./mvnw -pl oauth/auth-server spring-boot:run
# 2) Start protected resource: ./mvnw -pl oauth/quotes-protected-resource spring-boot:run
# 3) Execute requests in order, top to bottom.

@authServer = http://localhost:9090
@resourceServer = http://localhost:8081
@client_id = uppercase-quotes
@client_secret = uppercase-quotes

### Step 1: Exchange client credentials for an access token at the auth server token endpoint.
### IntelliJ HTTP client will compute `Basic base64(client_id:client_secret)` from the two values below.
POST {{authServer}}/oauth2/token
Authorization: Basic {{client_id}} {{client_secret}}
Content-Type: application/x-www-form-urlencoded
Accept: application/json

grant_type=client_credentials&scope=quotes.read
> {%
  client.global.set("access_token", response.body.access_token);
%}


### Step 2: Call protected resource endpoint /whoami with the Bearer access token.
### The endpoint returns user/token details extracted by Spring Security from the JWT.
GET {{resourceServer}}/whoami
Authorization: Bearer {{access_token}}
Accept: application/json
